### ISSUE TITLE
Setup Vagrant Install Configuration

### ISSUE THREAD

**Issue by Sonophoto** [Sonophoto/sioo#18]
like what we discussed on the phone.

**Comment by Sonophoto** [comment]
Working on that now. ThAnKs! 

Hold on... It says I need an OS "CD", you mean one of those old disc things???

**Comment by Sonophoto** [comment]
Note: Naming convention::
Case always matters.
Everything should be SiOO with three exceptions:
sioo_Functions();
sioo/ directories
sioo hardlink to SiOO executable.

**Comment by danielrmeyer** [comment]
Not sure about the 'OS CD' issue.  Make sure you have virtualbox and vagrant installed and it should work:

```
$ VBoxManage --version
4.3.28r100309
$ vagrant --version
Vagrant 1.7.4
```

**Comment by Sonophoto** [comment]
K, thanks.

**Comment by Sonophoto** [comment]
uh, oh I used 
VBoxManage --version
5.0.2r102096

vagrant --version
Vagrant 1.4.3

I'm using mint-linux which uses pushes from ubuntu i believe.

is that bad? This is why I fear python! lol.

**Comment by Sonophoto** [comment]
I found docs, I'll figure it out, thanks for the kickstart.
